#JDBC Configutation for Database Connection
jdbc.driverClassName=com.mysql.jdbc.Driver
jdbc.url=jdbc:mysql://database-1.cd4eqmkwmwz6.ap-northeast-1.rds.amazonaws.com:3306/accounts?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
jdbc.username=admin
jdbc.password=admin123

#Memcached Configuration For Active and StandBy Host
#For Active Host
memcached.active.host=vporifile-cache.2lld2l.cfg.apne1.cache.amazonaws.com
memcached.active.port=11211
#For StandBy Host
memcached.standBy.host=vporifile-cache.2lld2l.cfg.apne1.cache.amazonaws.com
memcached.standBy.port=11211

#RabbitMq Configuration
rabbitmq.address=amqps://b-f98d792b-9176-4d23-a14a-208240b78ac3.mq.ap-northeast-1.on.aws
rabbitmq.port=5671
rabbitmq.username=rabbit
rabbitmq.password=rabbitrabbit

#Elasticesearch Configuration
elasticsearch.host =vprosearch01
elasticsearch.port =9300
elasticsearch.cluster=vprofile
elasticsearch.node=vprofilenode
